/* SCHEDULED PLANS */ 

SELECT [NAME]
      ,[PATH_NAME]
      ,[STATE]
      ,[DESCRIPTION]
      ,[ID]
      ,[ENTIRE_SCHEDULES]
  FROM [SCDRunbook].[dbo].[SCHEDULED_PLANS_LIST]
  WHERE STATE = 'Enabled' AND
  ENTIRE_SCHEDULES IS NOT NULL