/* SCHEDULED PLANS */ 

SELECT ABAT_PATHNAMES.NAME, ABAT_SCHEDULES.TIMES, ABAT_PATHNAMES.PATH_NAME
FROM [SCDRunbook].[dbo].[ABAT_PATHNAMES] 
LEFT JOIN [SCDRunbook].[dbo].[ABAT_SCHEDULED_PLANS] 
	ON [SCDRunbook].[dbo].[ABAT_SCHEDULED_PLANS].ID = [SCDRunbook].[dbo].[ABAT_PATHNAMES].ID 
LEFT JOIN [SCDRunbook].[dbo].[ABAT_SCHEDULES] 
	ON [SCDRunbook].[dbo].[ABAT_SCHEDULES].ScheduleName = [SCDRunbook].[dbo].[ABAT_SCHEDULED_PLANS].SCHEDULE

WHERE 
[SCDRunbook].[dbo].[ABAT_PATHNAMES].[OBJECT_TYPE] = 'JobPlan' AND 
[SCDRunbook].[dbo].[ABAT_PATHNAMES].[PATH_NAME] LIKE '%Scheduled_Plans%' AND
[SCDRunbook].[dbo].[ABAT_SCHEDULED_PLANS].[SCHEDULE] LIKE '%WEEKDAY%'

ORDER BY [SCDRunbook].[dbo].[ABAT_PATHNAMES].NAME