USE [SCDRunbook]
GO

/****** Object:  View [dbo].[ABAT_INVENTORY_LIST]    Script Date: 11/28/2022 10:57:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW [dbo].[ABAT_INVENTORY_LIST] AS

SELECT
[NAME],
[PATH_NAME],
[STATE],
[DESCRIPTION],
'SCHEDULE_OR_TRIGGER' = ISNULL([ENTIRE_SCHEDULES],'N/A')
FROM [SCDRunbook].[dbo].[SCHEDULED_PLANS_LIST]

UNION

SELECT 

[NAME],
[PATH_NAME],
[STATE],
[DESCRIPTION],
'SCHEDULE_OR_TRIGGER' = 'ADHOC'
FROM [SCDRunbook].[dbo].[ADHOC_PLANS_LIST]

UNION

SELECT 

TP.[NAME],
TP.[PATH_NAME],
TP.[STATE],
TP.[DESCRIPTION],
'SCHEDULE_OR_TRIGGER' = ISNULL(ABAT_TRIGGERS.TRIGGERS,'N/A')
FROM [SCDRunbook].[dbo].[TRIGGERED_PLANS_LIST] TP

OUTER APPLY (
    SELECT STRING_AGG([SCDRunbook].[dbo].TranslateString(REPLACE(REPLACE([SCDRunbook].[dbo].TranslateString([SCDRunbook].[dbo].[ABAT_FILETRIGGERS].Description),'${',''),'}','')),'; ') WITHIN GROUP (ORDER BY NAME) as TRIGGERS FROM [SCDRunbook].[dbo].[ABAT_FILETRIGGERS]
	INNER JOIN [SCDRunbook].[dbo].[TRIGGERED_PLANS_LIST] ON [SCDRunbook].[dbo].[ABAT_FILETRIGGERS].TriggeredPlan = [SCDRunbook].[dbo].[TRIGGERED_PLANS_LIST].NAME  
    WHERE [SCDRunbook].[dbo].[ABAT_FILETRIGGERS].TriggeredPlan = TP.NAME
	
) AS ABAT_TRIGGERS(TRIGGERS)

GO

